### ISSUE TITLE
Pipeline Profile Launcher - to native exe

### ISSUE THREAD

**Issue by mechris1** [intel-retail/automated-self-checkout#263]
**Description**

- Move cmd client to native executable
- Docker go builder
- Script to start the profile launcher (./profile_launcher $PIPELINE_PROFILE)

**AC**

- [ ] 1. Move cmd client to native executable 
- [ ] 2. Docker go builder
- [ ] 3. Script to start the profile launcher (./profile_launcher $PIPELINE_PROFILE)
- [ ] 4. Update the Make file

**Tasks**

- [ ] 1. Remove cmd_client Dockerfile and make cmd client to native executable (@jim-wang-intel)

**Comment by jim-wang-intel** [comment]
Closed by PR #268
