### ISSUE TITLE
Spike: Backs River Integration with Intel DevCloud

### ISSUE THREAD

**Issue by NeethuES-intel** [intel-retail/automated-self-checkout#280]
AC:
•Developer Toolbox for Edge-AI
•Marketplace - Launch use case
•Videos and models
•Generate metrics

## Version

1.5.0

## Hardware configuration

Intel DevCloud

## Description

Integrate backs river with Intel DevCloud to align with their public release 

## Task

- [X] Sync up with Mrinal
- [x] Go through documentations
- [x] Apply for access
- [X] Sync with DevCloud team
