### ISSUE TITLE
PQ Tool Work [Sprint 2024-02]: Recurring User Story for project tracking

### ISSUE THREAD

**Issue by NeethuES-intel** [intel-retail/automated-self-checkout#495]
PQ Tool work @NeethuES-intel @jim-wang-intel 
- [ ] wpf/xaml/material-design training
- [X] development setup
- [X] mock UI
- [ ] weekly sync up
- [ ] konica camera exploration
- [ ] map day
