### ISSUE TITLE
Integrate RTSF with Backs River

### ISSUE THREAD

**Issue by NeethuES-intel** [intel-retail/automated-self-checkout#580]
Convert to OVMS

**Tasks**
- [x] Integrate OVMS for model inferencing instead of DL streamer pipeline-server @NeethuES-intel 
- [ ] Preprocess frames & send to ovms (grpc call) for model inferencing @NeethuES-intel 
- [ ] Postprocess to get roi coordinates & publish it to mqtt topic `AnalyticsData`
- [ ] Can pre & post processing be chained with inferencing by OVMS & only roi coordinates sent back to CV ROI service which are then published to mqtt topic  `AnalyticsData` ?

Based on discussions with Brian, updated architecture diagram -
![Image](https://github.com/intel-retail/automated-self-checkout/assets/3488970/9ebbb35a-bfa6-4cf9-8087-a06031c85643)
