### ISSUE TITLE
Loss Prevention: Add person detection and tracking with region of interest

### ISSUE THREAD

**Issue by antoniomtz** [intel-retail/automated-self-checkout#620]
- [x] Create LP pipeline for person detection and tracking
- [x] Add integration testing
- [x] Update documentation
- [x] Investigate Coffee bay repo

**Comment by antoniomtz** [comment]
Found and issue while running gvapython on 2024.1.2-dev-ubuntu24
We need this version since this supports YOLOv8 and gvaattachroi. 
I created an issue here https://github.com/dlstreamer/dlstreamer/issues/440
